import { Geist, Geist_Mono } from 'next/font/google';

import type { Metadata } from 'next';

import { QueryProvider } from '@/providers/QueryProvider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header style={{ padding: '1rem', background: 'red' }}>
          <h1>Global App Layout</h1>
        </header>
        <main style={{ padding: '1rem' }}>
          <QueryProvider>{children}</QueryProvider>
        </main>
      </body>
    </html>
  );
}
